### ISSUE TITLE
Installation failed (NodeJs 9.9.0)

### ISSUE THREAD

**Issue by maximang** [Adeptive/homebridge-soundtouch#26]
Hi,

I tried to install this Homebridge Plugin on my Raspberry Pi Zero running the latest version of NodeJs and Homebridge, but it's not working.

Here is what I see in the console:
`pi@raspberrypi:~/.homebridge $ sudo npm install -g homebridge-soundtouch

> mdns@2.4.0 install /usr/local/lib/node_modules/homebridge-soundtouch/node_modules/mdns
> node-gyp rebuild

gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.14.50+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-soundtouch/node_modules/mdns
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-22T19_55_06_071Z-debug.log`

And the **2018-07-22T19_55_06_071Z-debug.log** file:
[https://pastebin.com/Jc6Yy8LS](url)

Do you have any idea of what could be the problem?

Thanks in advance!

**Comment by Daniel-rpi** [comment]
Hi,

I've got a similar error by trying to install soundtouch plugin:

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.50-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/.npm-global/lib/node_modules/homebridge-soundtouch/node_modules/soundtouch/node_modules/mdns
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! mdns@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.4.0 install script.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.14.50-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-soundtouch"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

Can somebody give me an advise to solve this?

Many thanks!

**Comment by Adrenocortico** [comment]
I’ve got this problem too. Has anyone found a solution in these months?
