### ISSUE TITLE
Crashing with since new firmwares

### ISSUE THREAD

**Issue by mensa84** [Adeptive/homebridge-soundtouch#28]
Hello,

that plugin is crashing since new firmware for SoundTouch 20 was released (FW 20.0.6)).

Log:
```

Nov 23 06:43:01 Server homebridge[28366]: /usr/lib/node_modules/homebridge-soundtouch/node_modules/soundtouch/api.js:67
Nov 23 06:43:01 Server homebridge[28366]:         var isAlive =  json.nowPlaying.source != SOURCES.STANDBY;
Nov 23 06:43:01 Server homebridge[28366]:                                        ^
Nov 23 06:43:01 Server homebridge[28366]: TypeError: Cannot read property 'source' of undefined
Nov 23 06:43:01 Server homebridge[28366]:     at /usr/lib/node_modules/homebridge-soundtouch/node_modules/soundtouch/api.js:67:40
Nov 23 06:43:01 Server homebridge[28366]:     at /usr/lib/node_modules/homebridge-soundtouch/node_modules/soundtouch/api.js:363:17
Nov 23 06:43:01 Server homebridge[28366]:     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-soundtouch/node_modules/soundtouc                                                   h/utils/xmltojson.js:25:13)
Nov 23 06:43:01 Server homebridge[28366]:     at emitNone (events.js:111:20)
Nov 23 06:43:01 Server homebridge[28366]:     at IncomingMessage.emit (events.js:208:7)
Nov 23 06:43:01 Server homebridge[28366]:     at endReadableNT (_stream_readable.js:1064:12)
Nov 23 06:43:01 Server homebridge[28366]:     at _combinedTickCallback (internal/process/next_tick.js:139:11)
Nov 23 06:43:01 Server homebridge[28366]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Nov 23 06:43:01 Server systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Nov 23 06:43:01 Server systemd[1]: homebridge.service: Unit entered failed state.
Nov 23 06:43:01 Server systemd[1]: homebridge.service: Failed with result 'exit-code'.

```

**Comment by mensa84** [comment]
correct title
